### ISSUE TITLE
Examples are not satisfying

### ISSUE THREAD

**Issue by aslushnikov** [aslushnikov/ftree#20]
We should make a clean examples which illustrate the rendering engine.

Currently, half of the examples doesn't work, and another half is not satisfying.

**Comment by aslushnikov** [comment]
@sedrakk how about using the Kalashyan's tree as an example?

**Comment by aslushnikov** [comment]
as per offline discussion with @sedrakk:
- leave only armenian kalashyan tree as an example
- keep details in english and russian

**Comment by sedrakk** [comment]
done
