### ISSUE TITLE
Different layout of the sun tree with same parameters 

### ISSUE THREAD

**Issue by sedrakk** [aslushnikov/ftree#7]
see screenshots

![screenshot 2017-02-12 11 18 32](https://cloud.githubusercontent.com/assets/24441206/22865281/777cf874-f115-11e6-8ddb-c07c3cc53636.png)
![screenshot 2017-02-12 11 18 29](https://cloud.githubusercontent.com/assets/24441206/22865282/77995492-f115-11e6-9f10-3c79e6711314.png)

**Comment by aslushnikov** [comment]
The reason is that circles & text is 2x size in the canvas renderer. So to get the same visual representation on SVG, you have to cut half the sizes
