### ISSUE TITLE
Pixelated image

### ISSUE THREAD

**Issue by sedrakk** [aslushnikov/ftree#8]
<img width="1098" alt="screenshot 2017-02-17 14 03 00" src="https://cloud.githubusercontent.com/assets/24441206/23087414/0e9c305a-f529-11e6-8cf0-c80065939350.png">

you can see the original image in the left and how it looks like on the map on the right - it's stretched out by some reason

**Comment by aslushnikov** [comment]
Is that a screenshot from print.html?

**Comment by sedrakk** [comment]
nope, just check out family.kalashyan.com - you'll see same quality

**Comment by aslushnikov** [comment]
then, sure it's scaled up as you zoom. The maximum zoom is 1.5
