### ISSUE TITLE
Names of deceased should not be gray

### ISSUE THREAD

**Issue by sedrakk** [aslushnikov/ftree#9]
<img width="495" alt="screenshot 2017-02-17 14 03 12" src="https://cloud.githubusercontent.com/assets/24441206/23087450/5bd74eea-f529-11e6-83ba-7d4b9f46e3d5.png">

Names and DB are gray color in the same way as the circle. It should be black as all other names. Only circles should be grayed.

**Comment by aslushnikov** [comment]
You told to make them grey...

**Comment by sedrakk** [comment]
did i?
well in the production version it wasn't gray so i assume production version was the correct one..

**Comment by aslushnikov** [comment]
What's a production version? canvas?

**Comment by sedrakk** [comment]
yes

**Comment by aslushnikov** [comment]
No, they were grey with the canvas renderer. Check it out here: https://aslushnikov.github.io/ftree/#usecanvas

**Comment by sedrakk** [comment]
<img width="781" alt="screenshot 2017-02-17 15 58 41" src="https://cloud.githubusercontent.com/assets/24441206/23087546/f8c127a8-f529-11e6-97dc-feb082daead7.png">

they are not gray

**Comment by aslushnikov** [comment]
where do you get this screenshot from?

**Comment by sedrakk** [comment]
from your link

**Comment by aslushnikov** [comment]
Well that's funny, cause what i see is: 
![image](https://cloud.githubusercontent.com/assets/746130/23087599/54f5c6d2-f52a-11e6-93d7-68dc9cf9bd1e.png)

**Comment by sedrakk** [comment]
anyway, can we make them black..?

**Comment by aslushnikov** [comment]
sure!
